/*
- id: the ID of the user, can be auto-generated by MongoDB
- username: Username of the user
- email: Email of the user
- password: Encryption of the password
- joined_date: The date the user joined the site
- friend_list: The list of friends the user added
- post_history: The list of IDs of posts which belong to the user
- comment_history: The list of IDs of comments which belong to the user
- communities: The list of game IDs which the user subscribe to
- conversation: The list of conversation IDs which the user have
- is_creator: If the user is the creator of the site, it should be true
*/


const mongoose = require("mongoose");
const Schema = mongoose.Schema;

const UserSchema = new Schema({
    user_id: {
        type: Number,
        required: true,
    },
    username: {
        type: String,
        required: true,
    },
    email: {
        type: String,
        required: true,
    },
    password: {
        type: String,
        required: true,
    },
    join_date: {
        type: Date,
        required: true,
    },
    friend_list: {
        type: Array,
        required: true,
    },
    post_history: {
        type: Array,
        required: true,
    },
    comment_history: {
        type: Array,
        required: true,
    },
    communities: {
        type: Array,
        required: true,
    },
    conversations: {
        type: Array,
        required: true,
    },
    saved_games:{
        type: Array,
        required: true,
    },
    is_creator: {
        type: Boolean,
        required: true,
    },
    is_banned: {
        type: Boolean,
        required: true,
    },
    login_token: {
        type: String,
    },

}, {collection: 'userData'}); // Name of the collection

module.exports = Users = mongoose.model('userData', UserSchema);