/*
- id: the ID of the user, can be auto-generated by MongoDB
- username: Username of the user
- email: Email of the user
- password: Encryption of the password
- joined_date: The date the user joined the site
- friend_list: The list of friends the user added
- post_history: The list of IDs of posts which belong to the user
- comment_history: The list of IDs of comments which belong to the user
- communities: The list of game IDs which the user subscribe to
- conversation: The list of conversation IDs which the user have
- is_creator: If the user is the creator of the site, it should be true
*/
